customhost = "employee.cp1i7ednddox.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chongkaowei-employee"
customregion = "us-east-1"
